# Generated by Django 4.1.3 on 2023-05-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datamodel",
            old_name="APIWELLNUMBER",
            new_name="API_WELL_NUMBER",
        ),
    ]
